version: '2.4'

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/monitoring
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASSWORD}
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/monitoring
      SPRING_FLYWAY_USER: ${DB_USER_NAME}
      SPRING_FLYWAY_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy